### ISSUE TITLE
string-length.js verify code is incorrect.

### ISSUE THREAD

**Issue by Moser2010** [unioncollege-webtech/javascripting#5]
You ask us to create a file named string-length.js but than ask us to verify the code using javascripting verify sting-lingth.js    string != sting

**Comment by barberboy** [comment]
Hmm, can you send me a screenshot of where you saw sting-length.js? I must be looking in the wrong spot, because this is what I see:

![screen shot 2015-09-04 at 3 54 11 pm](https://cloud.githubusercontent.com/assets/371332/9694347/6fdc7956-531d-11e5-877e-0a03734cc0d1.png)

In both cases, it's using the file name "string-length.js".

**Comment by Moser2010** [comment]
I looked through it and didn't see what the issue was. I don't know why it didn't work before but I got it to work now.
